### ISSUE TITLE
[Bug] Use real semantic versioning

### ISSUE THREAD

**Issue by tabrindle** [tjbenton/docs#12]
The versioning scheme has changed multiple times, and alpha is not necessary. 

Since this is in production use, this package should use real semantic versioning, starting at 1.0.0, and changing as necessary.

**Comment by tjbenton** [comment]
Agreed, I didn't want to release version one until I removed the harp.js library from it because I know it's not a stable library to rely on long term. Also part of the semantic versioning problems were that it wasn't automated. Going forward it will use a library called [np](https://www.npmjs.com/package/np) which makes everything automated and is how `npm publish` should have been
